FROM python:3.11-slim
WORKDIR /opt/app
COPY requirements.txt /opt/app/
RUN python -m pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt apache-airflow==2.6.3
COPY . /opt/app
CMD ["bash","-c","airflow db init && airflow scheduler & airflow webserver"] 
