FROM python:3.11-slim AS builder
WORKDIR /app
COPY requirements.txt .
RUN python -m pip install --upgrade pip && pip wheel --no-deps --wheel-dir /wheels -r requirements.txt
FROM python:3.11-slim
WORKDIR /app
COPY --from=builder /wheels /wheels
RUN pip install --no-index --find-links /wheels -r requirements.txt
COPY . /app
CMD ["python", "-u", "app/processing/run_consumer.py"] 
