apiVersion: v1
kind: Service
metadata:
  name: {{ include "realtime-platform.fullname" . }}-producer
spec:
  type: ClusterIP
  selector:
    app: producer
  ports:
    - port: 80
      targetPort: 8000
