# Note: for production use managed Kafka (Confluent / MSK) or a proper K8s operator
apiVersion: v1
kind: Pod
metadata:
  name: kafka-placeholder
spec:
  containers:
  - name: placeholder
    image: confluentinc/cp-kafka:7.4.0
    command: ['sh','-c','sleep infinity']
